# Generated by Django 5.1.3 on 2024-11-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_minima',
            field=models.IntegerField(default=5),
        ),
    ]
